<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login</name>
   <tag></tag>
   <elementGuidId>a02fcc88-5331-43a3-97b7-861e55ac1a43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-button v-widget login-login-button v-button-login-login-button jm-login-page v-button-jm-login-page</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jmpreplogin-1850199929&quot;)/div[@class=&quot;v-ui v-scrollable&quot;]/div[@class=&quot;v-panel v-widget login-page-view v-panel-login-page-view v-has-width&quot;]/div[@class=&quot;v-panel-content v-panel-content-login-page-view v-scrollable&quot;]/div[@class=&quot;v-verticallayout v-layout v-vertical v-widget jm-login-page v-verticallayout-jm-login-page v-has-width&quot;]/div[@class=&quot;v-slot v-slot-loginLayout v-slot-jm-login-page v-slot-has-locale-selector v-align-center v-align-middle&quot;]/div[@class=&quot;v-csslayout v-layout v-widget loginLayout v-csslayout-loginLayout jm-login-page v-csslayout-jm-login-page has-locale-selector v-csslayout-has-locale-selector&quot;]/div[@class=&quot;v-horizontallayout v-layout v-horizontal v-widget login-fields-layout v-horizontallayout-login-fields-layout&quot;]/div[@class=&quot;v-slot v-slot-login-login-button v-slot-jm-login-page&quot;]/div[@class=&quot;v-button v-widget login-login-button v-button-login-login-button jm-login-page v-button-jm-login-page&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='jmpreplogin-1850199929']/div/div[2]/div[2]/div/div/div/div[6]/div[5]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[5]/div</value>
   </webElementXpaths>
</WebElementEntity>
