<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_33614</name>
   <tag></tag>
   <elementGuidId>56798cab-ec3f-4f9d-888e-9fc8a931bd7a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-grid-cell v-grid-cell-focused</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>33,614</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainLocation&quot;)/div[@class=&quot;v-csslayout v-layout v-widget main v-csslayout-main&quot;]/div[@class=&quot;v-customcomponent v-widget fw-page v-customcomponent-fw-page v-has-width&quot;]/div[@class=&quot;v-csslayout v-layout v-widget fw-pagelayout v-csslayout-fw-pagelayout searchComponent v-csslayout-searchComponent searchLayout v-csslayout-searchLayout&quot;]/div[@class=&quot;v-csslayout v-layout v-widget results v-csslayout-results expanded v-csslayout-expanded&quot;]/div[@class=&quot;v-csslayout v-layout v-widget gridContainer v-csslayout-gridContainer&quot;]/div[@class=&quot;v-grid v-widget grid v-grid-grid v-has-width v-has-height&quot;]/div[@class=&quot;v-grid-tablewrapper&quot;]/table[1]/tbody[@class=&quot;v-grid-body&quot;]/tr[@class=&quot;v-grid-row v-grid-row-focused v-grid-row-has-data&quot;]/td[@class=&quot;v-grid-cell v-grid-cell-focused&quot;]</value>
   </webElementProperties>
</WebElementEntity>
