<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_vaadiniframe</name>
   <tag></tag>
   <elementGuidId>dd3bfba6-e987-448f-92fc-362262c7cd84</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vaadiniframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kirona-def-2.kirona.com/jmtest/embedded?authToken=VUZJU1d5aWt5bjQ9IyNKT04uSEFURklFTEQjIzEjIzE1MjYyMjQzNzQ4NDk=&amp;authFailUrl=#!EntryPointView/entity=JOB/entityValue=null/operation=CREATE/maxwidth=1037/maxheight=719/entityTypesSupported=JMASSET%2CJMJOB/returnTo=/refreshable=false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vaadiniframe&quot;)</value>
   </webElementProperties>
</WebElementEntity>
