<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Job DetailTypeInspectionDu</name>
   <tag></tag>
   <elementGuidId>fc5f6e9a-4eb0-4295-86b0-77e442523868</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jmcontent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>layout-area</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>location</name>
      <type>Main</type>
      <value>jmcontent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job DetailTypeInspectionDuration External Reference 1External Reference 2SLAAttributesTest / Live*TestLiveRegion*AreaPriorityCategory CodeInspection Type*Customer Name*Customer PhoneCustomer EmailRegistration Number*ID Number*County Parish Holding (CPH) Number (00 / 000 / 0000)Exclude from OptimisationTrueFalseLast Inspection DateBusiness Type*Location+No locations defined for this jobAssets+No assets defined for this jobParties+No parties defined for this jobScheduling CriteriaScheduling Related WindowsSLA WindowNo SLA set on jobShortest Asset WindowNo Asset WindowScheduling WindowFollow SLA WindowExplicit Scheduling WindowFixed ResourceAuto SchedulableLines SummaryCreatePacker(0)-Batch Information(0)-Follow Up Inspections(0)Wholesaler(0)-Batch Information(0)-Follow Up Inspections(0)Producer(0)-Flock Details(0)-Follow Up Inspections(0)Collector(0)-Batch Information(0)-Follow Up Inspections(0)Hatchery / Rearer(0)-Follow Up Inspections(0)Processor(0)-Batch Information(0)-Follow Up Inspections(0)Auction Market(0)-Batch Information(0)-Follow Up Inspections(0)Hygiene Inspection(0)EMH03b(0)-Improvements Required(0)EMR04h(0)EMR06a(0)-Schedule Details(0)EMR06b(0)EMI58(0)-Contraventions / Actions(0)EMI59(0)EMI60(0)EMI61(0)Hen House Summary(0)Notes+Note:OKCancelAttachmentsAdd attachments - drag into drop areaDROPFILES...or choose filesAttachments:</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jmcontent&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FSM1/Control Centre/Create EMI Inspection/Create Address/Page_JM Control Centre/iframe_vaadiniframe</value>
   </webElementProperties>
</WebElementEntity>
