<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>df963d52-f950-4117-a4d5-8b8ee1fb4788</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-nativebutton-caption</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jmcontent&quot;)/div[@class=&quot;v-csslayout v-layout v-widget mainLayout v-csslayout-mainLayout&quot;]/div[@class=&quot;v-customcomponent v-widget v-has-width&quot;]/div[@class=&quot;v-csslayout v-layout v-widget formBuilderPanel v-csslayout-formBuilderPanel formBuilderPanelExpanded v-csslayout-formBuilderPanelExpanded formBuilderPanelExpandable v-csslayout-formBuilderPanelExpandable&quot;]/div[@class=&quot;v-ddwrapper v-widget&quot;]/div[@class=&quot;v-csslayout v-layout v-widget header v-csslayout-header&quot;]/button[@class=&quot;v-nativebutton v-widget add v-nativebutton-add&quot;]/span[@class=&quot;v-nativebutton-caption&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FSM1/Control Centre/Create EMI Inspection/SLA/Page_JM Control Centre (1)/iframe_vaadiniframe</value>
   </webElementProperties>
</WebElementEntity>
