<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_v-datefield-button</name>
   <tag></tag>
   <elementGuidId>58ff02f1-f82d-44d7-a7e0-0f852ae988b5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-datefield-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>gwt-uid-167</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jmcontent&quot;)/div[@class=&quot;v-csslayout v-layout v-widget mainLayout v-csslayout-mainLayout&quot;]/div[@class=&quot;v-customcomponent v-widget jm-standard-panel v-customcomponent-jm-standard-panel formBuilderPanel v-customcomponent-formBuilderPanel&quot;]/div[@class=&quot;v-csslayout v-layout v-widget k-csslayout v-csslayout-k-csslayout&quot;]/div[@class=&quot;v-csslayout v-layout v-widget k-csslayout v-csslayout-k-csslayout options v-csslayout-options&quot;]/div[@class=&quot;v-csslayout v-layout v-widget k-csslayout v-csslayout-k-csslayout components v-csslayout-components&quot;]/div[@class=&quot;v-csslayout v-layout v-widget k-csslayout v-csslayout-k-csslayout explicitWindow v-csslayout-explicitWindow&quot;]/div[@class=&quot;v-datefield v-datefield-popupcalendar v-widget v-datefield-error nicer-field v-datefield-nicer-field medium-field v-datefield-medium-field hasAnnotation v-datefield-hasAnnotation kirmins-0-15-30-45 v-datefield-kirmins-0-15-30-45 v-required v-datefield-required v-datefield-full&quot;]/button[@class=&quot;v-datefield-button&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FSM1/Control Centre/Page_JM Control Centre/iframe_vaadiniframe</value>
   </webElementProperties>
</WebElementEntity>
