<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Job Manager Control Centre_1</name>
   <tag></tag>
   <elementGuidId>7757ff38-bc6e-4984-84fc-1a5b3074edbe</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuLocation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>location</name>
      <type>Main</type>
      <value>menuLocation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job Manager Control Centre►OptionsJob Manager Control Centre►Jon Hatfield4,280DashboardViewTrackLatest PositionsToday's TracksYesterday's TracksPlanPortal ...PartiesIncidentsToolsProjectsToolbar >Settings ...Business >CreateRecents</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuLocation&quot;)</value>
   </webElementProperties>
</WebElementEntity>
