<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PMM Regression - Registration</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-12-21T12:22:49</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e5d6ef20-1417-4869-aa5e-79df12fa9fb4</testSuiteGuid>
   <testCaseLink>
      <guid>9ed4db28-cb8f-46ca-b9a7-1bb2410779cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/Launch Job Manager Control Centre</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>53f71fb4-eec6-43bd-8c17-d00a315937ac</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Pre Production/Environmental/UandP</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>53f71fb4-eec6-43bd-8c17-d00a315937ac</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>7e7a05b7-a8fe-4263-a211-ed7d0214de26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>53f71fb4-eec6-43bd-8c17-d00a315937ac</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>b38ba976-6133-4f9c-9a6f-8f2b4255ea5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dc3ac28-c9f2-41f2-90d4-368b3d76d301</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a546328-81b6-4fa1-b66e-42b20e7a5806</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PMM/Generic/Create PMM Inspection</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>988e98bb-83e0-46d3-9dce-5985048c8d03</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Pre Production/PMM/PMM Inspection Type</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>988e98bb-83e0-46d3-9dce-5985048c8d03</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Registration</value>
         <variableId>a8895616-6f03-433e-b22b-0694823549af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c2e7b75-af10-4ed2-a16f-84a0a2b1102e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/Launch Job Manager</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cb6b3d31-ba25-4643-94da-4e6b990d99d9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Pre Production/Environmental/UandP</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>cb6b3d31-ba25-4643-94da-4e6b990d99d9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>3d4f513b-8b02-4fb9-b880-2c2e951d8f69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cb6b3d31-ba25-4643-94da-4e6b990d99d9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>13e7929c-4cc0-4343-bb83-7779b5b87a8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cb6b3d31-ba25-4643-94da-4e6b990d99d9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>JMUsername</value>
         <variableId>2024dc9b-cb06-41b8-bb97-d017aea523ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cb6b3d31-ba25-4643-94da-4e6b990d99d9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>JMPassword</value>
         <variableId>c378ba3c-5e46-49f4-ad39-a46ad361e174</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0509a92-379e-4540-8708-b866ec98cc71</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f5bb83e4-9453-4413-9090-73188b0dd450</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/Select Inspection</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f59db667-0bc7-46b4-945d-a3250a8cde9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PMM/Registration/Complete PMM Inspection - Registration - Inspection Details</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>319fdb48-6dd9-476c-aa5b-440ef57c648e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PMM/Compliance/Complete PMM Inspection - Complete</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c706d80f-6d08-4e1e-abc8-dcca5fc18421</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/Launch Job Manager Control Centre - Check Result</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d514b134-4725-4b08-a2b4-b06e7b374d00</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Pre Production/Environmental/UandP</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d514b134-4725-4b08-a2b4-b06e7b374d00</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>9633dd6d-8d38-4770-99c6-d4c4736ba3da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d514b134-4725-4b08-a2b4-b06e7b374d00</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>9acaa269-a0a3-406d-bc7c-7ca8e7573278</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>647a4c54-3be1-4207-ae05-6f58ee7d6155</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9cce984d-f6e7-4fa2-b8dd-4eec799c1acb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PMM/Registration/Control Centre - Check Results - PMM Registration</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc1b7868-399a-4543-bef9-f920e2cd3683</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d9fc9ab-bd39-479e-afd9-bfc69c411f74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ABP/Generic/Check Subsequent Inspection Exist</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
